### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by CallumTarttelin** [SamDerp/maths-quiz#2]
Use mongo to store data.

**Comment by SamDerp** [comment]
mango did not work for storing data, have returned mango
http://www.mango.org/Mangos/media/Media/Images/Consumer%20Page%20Teaser/haden.png

**Comment by CallumTarttelin** [comment]
Mongo https://api.mongodb.com/python/current/

**Comment by SamDerp** [comment]
I deed eet
